# Site settings
title: Mahyar Onsori
email: mahyaronsori99@gmail.com
description: >-
  Personal blog and portfolio on embedded systems, image processing, travel, sports, and many more things!
github_username: "Mahyar426"
minimal_mistakes_skin: "aqua"
search: true

# Theme & Layout
theme: minimal-mistakes-jekyll
enable_copy_code_button: true

# Build settings
markdown: kramdown
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: "Europe/Rome"

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

collections:
  projects:
    output: true
    permalink: /projects/:name/

author:
  name: "Mahyar Onsori"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Embedded Systems Engineer by day, Sports Enthusiast by night."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Mahyar426"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mahyar-onsori/"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mahyar-onsori/"

defaults:
  - scope:
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author: Mahyar
  - scope:
      path: ""
      type: pages
    values:
      layout: home
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
